---
version: '3'
services:

# START SERVICE vcwc/elastic/metricbeat
  metricbeat:
    image: ${VCW_REGISTRY}vcwc/elastic.metricbeat:7.9.2
    environment: ['ES_METRICBEAT_LOGGING_LEVEL=${METRICS_MODULE_METRICBEAT_LOGGING_LEVEL}']
    command: []
    volumes: ['/etc:/hostfs/etc:ro','${VCW_STACK_GLOBAL_STACKPREFIX}_metricbeat_config:/vcw/pwd','${VCW_STACK_GLOBAL_STACKPREFIX}_metricbeat_volume:/usr/share/metricbeat/data']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${METRICS_DEPLOY_MODE}
      resources:
        limits:
          memory: '${METRICS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${METRICS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${METRICS_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/metricbeat

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_metricbeat_config: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_metricbeat_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
