---
version: '3'
services:

# START SERVICE vcwc/nginx/rewrite
  nginx:
    image: ${VCW_REGISTRY}vcw/nginx.base:${VCW_TAG}
    environment: ['VCW_STACK_NGINX_CONF_LOCATION=/${VCW_STACK_URLPREFIX}/kibana', 'VCW_STACK_NGINX_CONF_PROXY_PASS=${VCW_STACK_STACKPREFIX}_kibana:5601']
    command: []
    volumes: []
    ports: []
    networks: [${VCW_STACK_NETWORKGLOBAL}_overlay, ${VCW_STACK_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_EKG_UI_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_EKG_UI_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_NETWORKGLOBAL}_overlay,      traefik.http.services.${VCW_STACK_STACKPREFIX}_kibana.loadbalancer.server.port=80,      traefik.http.routers.${VCW_STACK_STACKPREFIX}_kibana.entrypoints=conteco,      traefik.http.routers.${VCW_STACK_STACKPREFIX}_kibana.rule=PathPrefix("/${VCW_STACK_URLPREFIX}/kibana")]
${VCW_STACK_EKG_UI_KIBANA_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/nginx/rewrite

networks: {${VCW_STACK_NETWORKGLOBAL}_overlay: { external: true }, ${VCW_STACK_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
